# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2

# Personal info
name: Dominic Minischetti
title: Full Stack Developer & Database Administrator
email: dominic.minischetti@gmail.com
# website: www.minischetti.me

# Dark Mode (true/false/never)
darkmode: true

# Social links
linkedin_username: dominischetti
twitter_username: dominischetti
instagram_username: dminischetti
facebook_username: dominic.minischetti
# github_username:  sproogen
# stackoverflow_username: "00000001"
# youtube_username: globalmtb

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Technical, dedicated professional with over 5 years of focused experience as a <mark>Data Analyst</mark> and <mark>SQL DBA</mark> with exceptional analytical, problem-solving, and communication skills looking for position within your organization in order to enhance my skills. 
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: New York City College of Technology
        caption: 2015 - 2020
        sub_title: Bachelor Degree
        description: Bachelor of Technology in Computer Systems, Database Specialization (GPA 3.7)
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Freelance
        sub_title: Full Stack Developer
        caption: August 2021 - Present
        description: | # this will include new lines to allow paragraphs
            - Full-Stack Developer (<mark>PHP</mark>/<mark>MySQL</mark>/<mark>Firebase</mark>/<mark>JS</mark>) responsible for building server-side web applications.
            - Troubleshooted issues affecting production, stage, and development environments using Agile Kanban through <mark>JIRA</mark> and <mark>GIT</mark> versioning systems for project management.
            - Played a key role in the feature implementation, development, improvement, and operation of web-based software using <mark>Nginx</mark> Application servers and <mark>Docker</mark> containers to deploy applications.
            - Identified, resolved, or provided recommendations on performance problems on multi-source replicas of <mark>Mariadb</mark> Database
      - layout: left
        title: Eiffel srl
        sub_title: Data Analyst and Database Administrator
        caption: November 2012 - October 2015
        description: | # this will include new lines to allow paragraphs
            - Responsible for providing database administration of <mark>SQL Server</mark> databases and mentoring less experienced administrators. 
            - Implemented SQL Server based solution to consolidate data collection and reporting applications.
            - Performed day to day DBA activities such as monitoring SQL Server, addressing user requirements. 
      - layout: left
        title: Call2U srl
        sub_title: Data Analyst
        caption: September 2010 - November 2012
        description: | # this will include new lines to allow paragraphs
            - Diagnosed, troubleshoot and resolved a range of software, hardware and connectivity issues. 
            - Transitioned, designed, tailored, installed, and maintained multiple instances of Service Manager in Windows with Microsoft SQL Server and <mark>T-SQL</mark> backends.
      - layout: left
        title: ASD Servizi
        sub_title: Web Developer
        caption: December 2006 - April 2008
        description: | # this will include new lines to allow paragraphs
            - Website creation and <mark>PHP</mark> Application Management, editing catalogs, editorial advertising, drafting advertising of web and paper for company image.
            - Responsible for all web services: design, renovation, banners, hosting and domain name registration.
            - Operator Panel and <mark>Plesk</mark> server maintenance and activation domains and mailboxes, <mark>SQL</mark> databases
  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
            | - Development languages: Java, C++, VBA, COBOL, Clipper |	- Analysis methodology: Functional Analysis, UML | - Application Server: Apache, IIS |
            | - Database: SQL Server, MySQL, Oracle, Access |	- Operative Systems: Windows, OSX, Unix|	- Graphic Development: Photoshop, Illustrator |
            | - Business Analytics: SSIS, Power BI | - Web: PHP, ASP, JavaScript, CSS, HTML ||
# Footer
footer_show_references: false
# references_title: References on request (Override references text)
# Build settings
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
#plugins:
# - jekyll-seo-tag
