# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2

# Personal info
name: Dominic Minischetti
title: Full Stack Developer
email: dominic.minischetti@gmail.com
website: www.minischetti.me

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: dominischetti
twitter_username: dominischetti
instagram_username: dminischetti
facebook_username: dominic.minischetti
# github_username:  sproogen
# stackoverflow_username: "00000001"
# youtube_username: globalmtb

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
about_title: About me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Experienced Full Stack Developer with over 5 years of professional experience in designing and developing web applications using PHP, JS, MySQL, and SQL Server. Skilled in troubleshooting and resolving issues, collaborating with cross-functional teams, and implementing effective solutions. Bachelor of Technology in Computer Information Systems with a focus on database management. Committed to staying current with emerging technologies and delivering seamless and intuitive interfaces that optimize system performance.
content:
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Full Stack Developer
        sub_title: Polished.Com Inc
        caption: May 2022 - Present
        description: | # this will include new lines to allow paragraphs
            - Designed and developed a Warehouse Management System using <mark>PHP</mark>, <mark>JS</mark>, and <mark>MySQL</mark>.
            - Created an intuitive interface for the mobile application of the warehouse system.
            - Collaborated with cross-functional teams to ensure optimal system performance.
            - Contributed to the seamless management of the warehouse system for company success.
      - layout: left
        title: Full Stack Developer
        sub_title: Kingsleague GmbH
        caption: August 2021 - May 2022
        description: | # this will include new lines to allow paragraphs
            - Built server-side web applications using <mark>PHP</mark>, <mark>MySQL</mark>, <mark>Firebase</mark>, and <mark>JS</mark>.
            - Troubleshot using Agile Kanban via <mark>JIRA</mark> and <mark>GIT</mark> for versioning.
            - Implemented, developed, and optimized web software with <mark>Nginx</mark> and <mark>Docker</mark> for deployment.
            - Identified and fixed performance issues on multi-source <mark>Mariadb</mark> replicas.
      - layout: left
        title: DBA & Data Analyst
        sub_title: Eiffel srl
        caption: November 2012 - October 2015
        description: | # this will include new lines to allow paragraphs
            - Administered <mark>SQL Server</mark> databases and provided tutoring to less experienced administrators.
            - Implemented SQL Server-based solutions for data consolidation and reporting.
            - Handled daily database administration tasks, including monitoring <mark>SQL Server</mark> and managing user requests.
      - layout: left
        title: Data Analyst
        sub_title: Call2U srl
        caption: September 2010 - November 2012
        description: | # this will include new lines to allow paragraphs
            - Diagnosed and resolved software, hardware, and connectivity issues.
            - Transferred, designed, adapted, installed, and maintained multiple instances of <mark>Service Manager</mark> on Windows platform using <mark>Microsoft SQL Server</mark> as <mark>T-SQL</mark> backend.
      - layout: left
        title: Frontend Developer
        sub_title: ASD Servizi
        caption: December 2006 - April 2008
        description: | # this will include new lines to allow paragraphs
            - Created websites and <mark>PHP</mark> applications, managed catalogs, and performed editorial advertising and copywriting for corporate image.
            - Responsible for the design and maintenance of web services, including banner ads, hosting, domain name registration.
            - Managed operator panel, Plesk server maintenance, domain and mailbox activation, and <mark>SQL</mark> database management.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: New York City College of Technology
        caption: 2020
        sub_title: Bachelor Degree (GPA 3.7/4)
        description: Bachelor of Technology in Computer Systems, Database Specialization. <br>Developed data analysis skills using <mark>Oracle SQL Developer</mark> and <mark>Microsoft SQL Server</mark> for designing and implementing multiple database management systems.
      - layout: left
        title: University of Bari, Bari, Italy
        caption: 2000
        sub_title: Coursework in Computer Science
        description: Acquired skills in designing, developing, and implementing software using programming languages such as <mark>Java</mark>, <mark>C++</mark>, and <mark>Python</mark>.
  - title: Additional Courses # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        - <b>MongoDB Course</b>, MongoDB University, 2021
        - <b>Project Management Course</b>, New York City College of Technology, 2019
        
        <!--table><tr><td width="50%"--><ul>
        <li><b>MongoDB Course</b>, MongoDB University, 2021</li>
        <li><b>Project Management Course</b>, New York City College of Technology, 2019</li>
        </ul><!--/td></tr></table-->
  - title: Technical Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        <!--table><tr><td width="50%"--><ul>
        <li><b>Programming languages:</b> PHP, Python, JavaScript</li>
        <li><b>Framework and libraries:</b> Bootstrap, jQuery, Smarty</li>
        <li><b>Development architecture:</b> Model-View-Controller (MVC)</li>
        <!--/ul></td>
        <td width="50%"><ul-->
        <li><b>API Development:</b> REST API</li>
        <li><b>Databases:</b> SQL Server, MySQL, MariaDB, MongoDB</li>
        <li><b>Development metodology:</b> Agile, Kanban</li>
        <li><b>Operating systems and servers:</b> Linux, Apache</li>
        </ul><!--/td></tr></table-->
  - title: Soft Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        <!--table><tr><td width="50%"--><ul>
          <li>Effective teamworking</li>
          <li>Clear and concise communication</li>
          <li>Efficient time management</li>
          <li>Adaptability and flexibility</li>
          <li>Creative problem-solving abilities</li>
          <li>Results-driven mindset</li>
          <li>Commitment to self-learning and continuous improvement</li>
        </ul><!--/td></tr></table-->
  - title: Languages # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        <!--table><tr><td width="50%"--><ul>
        <li>Italian (native speaker)</li>
        <li>English (fluent)</li>
        <li>Spanish (elementary level)</li>
        </ul><!--/td></tr></table-->
# Footer
footer_show_references: false
# references_title: References on request (Override references text)
# Build settings
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
#plugins:
# - jekyll-seo-tag
