# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2

# Personal info
name: Dominic Minischetti
title: Full Stack Developer & Database Administrator
email: dominic.minischetti@gmail.com
website: www.minischetti.me

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: dominischetti
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: dominic.minischetti
# flickr_username: jekyll
instagram_username: dminischetti
linkedin_username: dominischetti
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Technical, dedicated professional with over 5 years of focused experience as a <mark>Data Analyst</mark> and <mark>SQL DBA</mark> with exceptional analytical, problem-solving, and communication skills looking for position within your organization in order to enhance my skills. 
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Freelance
        sub_title: Full Stack Developer
        caption: August 2021 - Present
        description: | # this will include new lines to allow paragraphs
            - Full-Stack Developer (PHP/MySQL/Firebase/JS) responsible for building server-side web applications.
            - Troubleshooted issues affecting production, stage, and development environments using Agile Kanban through JIRA and GIT versioning systems for project management.
            - Played a key role in the feature implementation, development, improvement, and operation of web-based software using Nginx Application servers and Docker containers to deploy applications.
            = Identified, resolved, or provided recommendations on performance problems on multi-source replicas of Mariadb Database
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: New York City College of Technology
        caption: 2015 - 2020
        sub_title: Bachelor Degree
        description: Bachelor of Technology in Computer Systems, Database Specialization
# Footer
footer_show_references: true
# references_title: References on request (Override references text)
# Build settings
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
#plugins:
# - jekyll-seo-tag
