# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# Content configuration version
version: 2

# Personal info
name: Dominic Minischetti
title: Full Stack Developer
email: dominic.minischetti@gmail.com
website: www.minischetti.me

# Dark Mode (true/false/never)
darkmode: true

# Social links
linkedin_username: dominischetti
twitter_username: dominischetti
instagram_username: dminischetti
facebook_username: dominic.minischetti
# github_username:  sproogen
# stackoverflow_username: "00000001"
# youtube_username: globalmtb

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
about_title: Chi Sono
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Full Stack Developer con 5+ anni di esperienza nella progettazione di applicazioni web utilizzando <mark>PHP</mark>, <mark>JS</mark>, <mark>MySQL</mark> e <mark>SQL Server</mark>. Abile nel risolvere problemi e lavorare in team interfunzionali. Laureato in Tecnologia dell'Informazione con una specializzazione in Databases. Sempre alla ricerca di tecnologie emergenti per creare interfacce intuitive e prestazioni ottimizzate.
content:
  - title: Esperienza Professionale # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Full Stack Developer
        sub_title: Polished.Com Inc
        caption: Maggio 2022 - Presente
        description: | # this will include new lines to allow paragraphs
            - Progettazione e sviluppo del Sistema di Gestione di Magazzino con <mark>PHP</mark>, <mark>JS</mark> e <mark>MySQL</mark>
            - Creazione di un'interfaccia intuitiva per l'applicazione di magazzino su dispositivi portatili
            - Collaborazione con team interfunzionali per garantire prestazioni ottimali del sistema
            - Contributo alla gestione senza soluzione di continuità del sistema di gestione del magazzino per il successo dell'azienda
      - layout: left
        title: Full Stack Developer
        sub_title: Kingsleague GmbH
        caption: Agosto 2021 - Maggio 2022
        description: | # this will include new lines to allow paragraphs
            - Costruzione di applicazioni web lato server con <mark>PHP</mark>, <mark>MySQL</mark>, <mark>Firebase</mark> e <mark>JS</mark>
            - Risoluzione di problemi utilizzando Agile Kanban tramite <mark>JIRA</mark> e <mark>GIT</mark> per il versionamento
            - Implementazione di funzionalità, sviluppo e ottimizzazione di software web con <mark>Nginx</mark> e <mark>Docker</mark> per il deployment
            - Identificazione e risoluzione di problemi di prestazioni su repliche multi-source di <mark>Mariadb</mark>
      - layout: left
        title: Data Analyst e DBA
        sub_title: Eiffel srl
        caption: Novembre 2012 - Ottobre 2015
        description: | # this will include new lines to allow paragraphs
            - Amministrazione dei database <mark>SQL Server</mark> e tutoraggio degli amministratori meno esperti
            - Implementazione di soluzioni basate su <mark>SQL Server</mark> per consolidare l'acquisizione e la segnalazione dei dati
            - Amministrazione quotidiana del database, come il monitoraggio di <mark>SQL Server</mark> e la gestione delle richieste degli utenti
      - layout: left
        title: Data Analyst
        sub_title: Call2U srl
        caption: Settembre 2010 - Novembre 2012
        description: | # this will include new lines to allow paragraphs
            - Diagnostica e risoluzione di problemi software, hardware e di connettività. 
            - Trasferimento, progettazione, adattamento, installazione e manutenzione di molteplici istanze di <mark>Service Manager</mark> su piattaforma Windows con utilizzo di <mark>Microsoft SQL Server</mark> come backend <mark>T-SQL</mark>.
      - layout: left
        title: Frontend Developer
        sub_title: ASD Servizi
        caption: Dicembre 2006 - Aprile 2008
        description: | # this will include new lines to allow paragraphs
            - Creazione di siti web e applicazioni <mark>PHP</mark>, gestione di cataloghi, pubblicità editoriale e copywriting per l'immagine aziendale
            - Responsabile del design e della manutenzione di tutti i servizi web, inclusi banner pubblicitari, hosting e registrazione di nomi di dominio
            - Gestione della manutenzione del pannello operatore e del server <mark>Plesk</mark>, nonché attivazione di domini e caselle di posta elettronica e database <mark>SQL</mark>.
  - title: Formazione # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: New York City College of Technology
        caption: 2020
        sub_title: Bachelor Degree (GPA 3.7/4)
        description: Bachelor of Technology in Computer Systems, Database Specialization<br>
          Esperienza nello sviluppo di abilità di analisi dei dati in <mark>Oracle SQL Developer</mark> e <mark>Microsoft SQL Server</mark> per la progettazione e implementazione di più sistemi di gestione di database.
      - layout: left
        title: Università degli Studi di Bari, Bari, Italia
        caption: 2000
        sub_title: Corsi in Informatica
        description: Acquisizione di competenze nella progettazione, sviluppo e implementazione di software utilizzando linguaggi di programmazione come <mark>Java</mark>, <mark>C++</mark> e <mark>Python</mark>.
  - title: Corsi Aggiuntivi # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        <!--table><tr><td width="50%"--><ul>
        <li><b>Corso di MongoDB</b>, MongoDB University, 2021</li>
        <li><b>Corso di Project Management</b>, New York City College of Technology, 2019</li>
        </ul><!--/td></tr></table-->
  - title: Competenze Tecniche # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        <!--table><tr><td width="50%"--><ul>
        <li>Linguaggi di programmazione: PHP, Python, JavaScript</li>
        <li>Framework e librerie: Bootstrap, jQuery, Smarty</li>
        <li>Architettura di sviluppo: Model-View-Controller (MVC)</li>
        <!--/ul></td>
        <td width="50%"><ul-->
        <li>Sviluppo di API: REST API</li>
        <li>Database: SQL Server, MySQL, MariaDB, MongoDB</li>
        <li>Metodologia di sviluppo: Agile</li>
        <li>Conoscenze di base di sistemi operativi e server: Linux, Apache</li>
        </ul><!--/td></tr></table-->
  - title: Soft Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        <!--table><tr><td width="50%"--><ul>
        <li>Capacità di lavorare in team</li>
        <li>Comunicazione efficace</li>
        <li>Gestione del tempo</li>
        <li>Adattabilità ai cambiamenti</li>
        <li>Risoluzione creativa dei problemi</li>
        <li>Orientamento al risultato</li>
        <li>Capacità di apprendimento autonomo e di miglioramento continuo</li>
        </ul><!--/td></tr></table-->
  - title: Lingue Conosciute # Title for the section
    layout: text # Type of content section (list/text)
    content: |
        <!--table><tr><td width="50%"--><ul>
        <li>Italiano (madrelingua)</li>
        <li>Inglese (madrelingua)</li>
        <li>Spagnolo (elementare)</li>
        </ul><!--/td></tr></table-->
# Footer
footer_show_references: false
# references_title: References on request (Override references text)
# Build settings
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
#plugins:
# - jekyll-seo-tag
