# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dominic Minischetti
title: Full Stack Developer & Database Administrator
email: dominic.minischetti@gmail.com
website: www.minischetti.me

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: dominischetti
# github_username:  sproogen
# stackoverflow_username: "00000001"
facebook_username: dominic.minischetti
instagram_username: dminischetti
linkedin_username: dominischetti
# youtube_username: globalmtb

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Technical, dedicated professional with over 5 years of focused experience as a Data Analyst and SQL DBA with exceptional analytical, problem-solving, and communication skills looking for position within your organization in order to enhance my skills. 

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CUNY New York City College of Technology
        caption: 2015 - 2020
        sub_title: Bachelor's Degree
        description: | # this will include new lines to allow paragraphs
          Bachelor of Technology in Computer Systems, Database Specialization (GPA: 3.7/4)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Freelance
        sub_title: Full Stack Developer
        caption: August 2021 - Present
        description: | 
        -	Full-Stack Developer (PHP/MySQL/Firebase/JS) responsible for building server-side web applications.
        -	Troubleshooted issues affecting production, stage, and development environments using Agile Kanban through JIRA and GIT versioning systems for project management.
        -	Played a key role in the feature implementation, development, improvement, and operation of web-based software using Nginx Application servers and Docker containers to deploy applications.
        -	Identified, resolved, or provided recommendations on performance problems on multi-source replicas of Mariadb Database. 

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
